// ─────────────────────────────────────────────────────────────────────────────
// DOCUMENTATION DATA
// Centralized documentation entries for the Help Center
// ─────────────────────────────────────────────────────────────────────────────

export interface DocumentationEntry {
  id: string;
  title: string;
  category: string;
  shortDescription: string;
  purpose: string;
  howToUse: string[];
  importantActions: string[];
  tips: string[];
  commonMistakes: string[];
  updated: string;
}

export const DOCUMENTATION_ENTRIES: DocumentationEntry[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    category: "Overview",
    shortDescription: "Central hub for system monitoring and quick access to all modules",
    purpose: "Provides at-a-glance view of system status, recent activities, and key metrics. Serves as the entry point for navigating RCC OMP portal.",
    howToUse: [
      "Access Dashboard by clicking the Dashboard icon in the main navigation menu",
      "View system status widgets showing operational health and activity metrics",
      "Check recent activities and notifications from the activity feed",
      "Use quick action buttons to navigate to frequently used modules",
      "Monitor system performance indicators and alerts",
      "Review today's schedule and upcoming maintenance windows",
    ],
    importantActions: [
      "System Status Widget - Shows overall portal health (Operational/Degraded/Error)",
      "Recent Activities - Displays latest system events and user actions",
      "Quick Actions - Shortcuts to frequently used modules like Backup and Maintenance",
      "Notifications - Bell icon shows unread notifications and alerts",
    ],
    tips: [
      "Bookmark the Dashboard for quick access from browser favorites",
      "Check Dashboard first thing in the morning to review overnight activities",
      "Use the activity feed to track who made changes and when",
      "Pay attention to degraded service warnings - they may require investigation",
      "Dashboard auto-refreshes; no manual refresh needed",
    ],
    commonMistakes: [
      "Don't ignore system status warnings - investigate degraded services immediately",
      "Don't assume activities are complete without checking the notification center",
      "Remember that Dashboard shows real-time data - actual metrics may vary",
      "Avoid opening too many tabs simultaneously to prevent performance issues",
    ],
    updated: "today",
  },
  {
    id: "preventive-maintenance",
    title: "Preventive Maintenance",
    category: "System Management",
    shortDescription: "Schedule and manage preventive maintenance tasks for system reliability",
    purpose: "Ensures systems receive regular maintenance to prevent failures, extend lifespan, and maintain optimal performance. Helps track maintenance history and compliance.",
    howToUse: [
      "Navigate to Preventive Maintenance from the main navigation menu",
      "View all scheduled maintenance tasks in the calendar or list view",
      "Click 'Schedule Maintenance' to create a new maintenance task",
      "Select maintenance type (Hardware Check, Software Update, System Cleanup, etc.)",
      "Choose affected systems or departments from the dropdown",
      "Set frequency (One-time, Weekly, Monthly, Quarterly, Annually)",
      "Assign responsible personnel from the team list",
      "Add notes and attach relevant documentation if needed",
      "Confirm and save the maintenance schedule",
      "Monitor task completion status as maintenance is performed",
    ],
    importantActions: [
      "Schedule Maintenance - Create new maintenance tasks",
      "View Calendar - See all maintenance schedules by date",
      "Mark Complete - Record maintenance task completion with notes",
      "Add Resource - Attach documentation or procedures for technicians",
      "Generate Report - Create maintenance history reports for compliance",
      "Send Reminder - Notify assigned personnel before maintenance window",
    ],
    tips: [
      "Schedule maintenance during low-usage hours or designated maintenance windows",
      "Use templates for recurring maintenance tasks to save time",
      "Keep detailed notes about maintenance performed for future reference",
      "Set reminders 24 hours before critical maintenance tasks",
      "Review maintenance history quarterly to identify patterns or recurring issues",
      "Attach standard operating procedures (SOPs) to maintenance tasks",
    ],
    commonMistakes: [
      "Don't schedule critical maintenance during peak business hours",
      "Don't forget to mark tasks complete - this affects compliance records",
      "Remember that frequency settings must match your organizational policy",
      "Avoid scheduling multiple critical maintenance tasks simultaneously",
      "Don't ignore maintenance backlogs - they indicate system stress",
    ],
    updated: "today",
  },
  {
    id: "backup-activities",
    title: "Backup Activities",
    category: "Data Management",
    shortDescription: "Monitor, manage, and verify all system backup operations and storage",
    purpose: "Tracks backup job executions, verifies backup integrity, manages backup storage, and ensures data recovery capability. Critical for business continuity.",
    howToUse: [
      "Open Backup Activities from the navigation menu",
      "View all backup jobs with their status (Completed, Running, Failed, Scheduled)",
      "Click on any backup job to see detailed logs and verification results",
      "Use the status filters to view only relevant backups (e.g., show only failed)",
      "Create a new backup job by clicking 'New Backup Job'",
      "Configure backup parameters: source, destination, frequency, retention",
      "Test backup integrity using 'Verify Backup' option",
      "Download backup logs for auditing purposes",
      "Monitor backup storage usage and cleanup old backups if needed",
    ],
    importantActions: [
      "View Status - Check real-time backup job execution status",
      "Verify Backup - Run integrity checks on completed backups",
      "Download Logs - Export backup logs for compliance and auditing",
      "New Backup Job - Create additional backup tasks",
      "Retry Failed - Automatically retry failed backup jobs",
      "Storage Usage - Monitor backup storage capacity and cleanup",
    ],
    tips: [
      "Schedule backups during off-peak hours to minimize system impact",
      "Verify critical backups immediately after completion",
      "Store backup logs for at least 90 days per most compliance standards",
      "Keep at least 2 backup copies in different physical locations",
      "Review backup sizes regularly - sudden growth may indicate issues",
      "Test restore procedures quarterly to ensure backup validity",
    ],
    commonMistakes: [
      "Don't ignore failed backup notifications - address them immediately",
      "Remember that backup status 'Completed' doesn't mean backup is valid - verify it",
      "Don't let backup storage fill up - monitor capacity proactively",
      "Avoid assuming backups are encrypted - verify encryption settings explicitly",
      "Don't forget to retain backup logs - they're needed for audits",
    ],
    updated: "today",
  },
  {
    id: "monthly-hard-disk-tracker",
    title: "Monthly Hard Disk Tracker",
    category: "Hardware Monitoring",
    shortDescription: "Track monthly hard disk usage, capacity, and health metrics across systems",
    purpose: "Monitors disk utilization trends, predicts capacity issues, and helps plan storage upgrades. Prevents system outages due to full disks.",
    howToUse: [
      "Navigate to Monthly Hard Disk Tracker from the menu",
      "Select month and year to view tracking period",
      "View summary dashboard showing total usage across all systems",
      "Click on individual systems to see detailed disk metrics",
      "View capacity trend graphs showing growth patterns",
      "Identify systems with high usage (typically > 80%) that need attention",
      "Export monthly reports for capacity planning discussions",
      "Set thresholds to receive alerts when usage exceeds safe limits",
    ],
    importantActions: [
      "View Monthly Report - See disk usage summary for entire month",
      "System Details - Drill down into individual system metrics",
      "Trend Analysis - Identify growth patterns and project future capacity",
      "Set Threshold - Configure alerts for high-usage conditions",
      "Export Report - Create reports for stakeholders and planning",
      "Compare Months - View year-over-year changes in disk usage",
    ],
    tips: [
      "Review disk usage monthly to identify trends early",
      "Systems approaching 85% capacity should be addressed soon",
      "Use trend data to forecast when storage upgrades will be needed",
      "Set alerts at 75% capacity to give sufficient warning before critical levels",
      "Archive old data regularly to keep disk usage manageable",
      "Compare metrics month-to-month to identify unusual spikes",
    ],
    commonMistakes: [
      "Don't wait until disk is 95% full - start cleanup at 85%",
      "Remember that system performance degrades significantly over 90% capacity",
      "Avoid assuming growth rates remain constant - seasonal patterns exist",
      "Don't ignore temporary storage usage spikes - investigate their cause",
      "Remember to factor in backup storage when planning total capacity",
    ],
    updated: "today",
  },
  {
    id: "qa-activities",
    title: "QA Activities",
    category: "Quality Assurance",
    shortDescription: "Manage quality assurance tests, results, and compliance documentation",
    purpose: "Tracks QA test execution, documents test results, manages quality compliance, and ensures software meets quality standards before deployment.",
    howToUse: [
      "Open QA Activities module from the navigation",
      "View all active QA test suites and their status",
      "Click 'New Test Suite' to create a new QA test plan",
      "Add individual test cases with step-by-step instructions",
      "Assign testers and set deadline for test completion",
      "Execute tests and log results (Pass/Fail) with detailed notes",
      "Review failed tests and track remediation actions",
      "Generate QA report summarizing test coverage and results",
      "Archive completed test results for compliance records",
    ],
    importantActions: [
      "New Test Suite - Create new QA test plans",
      "Execute Test - Run individual test cases",
      "Log Results - Document test results and observations",
      "Track Issues - Log bugs and quality issues found",
      "Generate Report - Create QA compliance and coverage reports",
      "Approve Release - Sign off on QA completion before production deployment",
    ],
    tips: [
      "Always document failed tests with reproduction steps for developers",
      "Use standard test templates for consistent QA across teams",
      "Track test execution time to optimize future test planning",
      "Include regression testing in every test suite",
      "Document any environment-specific issues separately",
      "Review QA metrics quarterly to identify improvement opportunities",
    ],
    commonMistakes: [
      "Don't skip test documentation - it's critical for compliance",
      "Remember that test passing doesn't mean bug-free - test thoroughly",
      "Don't deploy with outstanding critical QA issues",
      "Avoid creating test suites that are too large - break into smaller chunks",
      "Don't forget to include edge cases and error conditions in tests",
    ],
    updated: "today",
  },
  {
    id: "system-inventory",
    title: "System Inventory",
    category: "Asset Management",
    shortDescription: "Maintain comprehensive inventory of all IT assets, hardware, and software",
    purpose: "Tracks all IT assets including servers, workstations, network equipment, and software licenses. Supports asset lifecycle management and compliance.",
    howToUse: [
      "Navigate to System Inventory from the main menu",
      "View all assets organized by category (Hardware, Software, Network, etc.)",
      "Click on any asset to view detailed specifications and history",
      "Add new asset by clicking 'Register New Asset'",
      "Fill in asset details: type, model, serial number, purchase date, location",
      "Assign asset to department or responsible person",
      "Track asset status (Active, Inactive, In Maintenance, Decommissioned)",
      "Update asset information as changes occur",
      "Generate inventory reports for compliance and audits",
    ],
    importantActions: [
      "Register Asset - Add new hardware or software to inventory",
      "Update Status - Change asset status as lifecycle progresses",
      "View Details - See complete asset information and history",
      "Assign Owner - Designate responsible personnel for asset",
      "Generate Report - Create inventory reports for audits",
      "Track Depreciation - Monitor asset value over time",
    ],
    tips: [
      "Maintain accurate serial numbers for warranty and support purposes",
      "Update asset location immediately when moved",
      "Document purchase dates and warranty information for compliance",
      "Review inventory quarterly to identify obsolete or unused assets",
      "Use barcode/QR codes for quick asset identification and tracking",
      "Keep backup of critical asset data for disaster recovery",
    ],
    commonMistakes: [
      "Don't lose track of assets after purchase - update inventory immediately",
      "Remember that warranty periods affect support options",
      "Avoid duplicate entries for the same asset",
      "Don't ignore decommissioned assets - track their disposal properly",
      "Remember to update inventory when assets are replaced or upgraded",
    ],
    updated: "today",
  },
  {
    id: "inspection-schedule",
    title: "Inspection Schedule",
    category: "Operations",
    shortDescription: "Plan and track facility and system inspections with comprehensive scheduling",
    purpose: "Coordinates facility inspections, compliance audits, and system reviews. Ensures all systems are regularly inspected and certified per regulatory requirements.",
    howToUse: [
      "Open Inspection Schedule from the navigation menu",
      "View upcoming inspections in calendar or list format",
      "Click on any inspection to see details and assigned personnel",
      "Create new inspection by clicking 'Schedule Inspection'",
      "Select inspection type (Safety Audit, Compliance Check, Equipment Inspection, etc.)",
      "Choose inspection scope and affected systems/areas",
      "Assign inspector and set scheduled date",
      "Add inspection checklist items and requirements",
      "Track inspection completion and document findings",
      "Generate compliance certificates after successful inspections",
    ],
    importantActions: [
      "Schedule Inspection - Create new inspection tasks",
      "View Details - See inspection requirements and history",
      "Assign Inspector - Designate personnel to conduct inspection",
      "Document Findings - Record inspection results and issues",
      "Generate Certificate - Create compliance documentation",
      "Track Remediation - Monitor resolution of inspection findings",
    ],
    tips: [
      "Schedule inspections during low-usage periods to minimize disruption",
      "Use standardized checklists for consistency across inspections",
      "Document all findings thoroughly with photos if applicable",
      "Follow up on remediation items to ensure compliance",
      "Maintain inspection records for at least 3 years per regulations",
      "Schedule follow-up inspections based on previous findings",
    ],
    commonMistakes: [
      "Don't schedule inspections too close together - allow time for remediation",
      "Remember that compliance requires documented evidence of inspections",
      "Don't overlook minor findings - they can become major issues",
      "Avoid rushing inspections - thorough documentation is critical",
      "Don't forget to assign qualified inspectors with proper certifications",
    ],
    updated: "today",
  },
  {
    id: "notifications",
    title: "Notifications",
    category: "Communication",
    shortDescription: "Manage system notifications, alerts, and communication preferences",
    purpose: "Centralizes system alerts, maintenance notifications, and important announcements. Helps users stay informed about critical system events.",
    howToUse: [
      "Access Notifications from the header or navigation menu",
      "View bell icon to see unread notification count",
      "Click notification center to view all recent notifications",
      "Review notification details by clicking individual alerts",
      "Mark notifications as read or archive them",
      "Set notification preferences in Settings menu",
      "Configure which event types trigger notifications",
      "Choose notification delivery method (In-app, Email, SMS)",
      "Set quiet hours to avoid notifications during off-hours",
    ],
    importantActions: [
      "View All - See complete notification history and status",
      "Mark Read - Clear unread notification indicators",
      "Archive - Remove read notifications from active list",
      "Preferences - Configure notification rules and delivery",
      "Critical Only - Filter to show only high-priority alerts",
      "Mute Category - Temporarily disable notifications for specific types",
    ],
    tips: [
      "Enable email notifications for critical alerts to receive out-of-app alerts",
      "Set quiet hours to avoid night-time notifications",
      "Archive old notifications regularly to keep notification center clean",
      "Review notification preferences monthly to ensure they match your needs",
      "Enable SMS for critical alerts that require immediate attention",
      "Use notification filters to focus on relevant information",
    ],
    commonMistakes: [
      "Don't ignore critical system alerts - they indicate problems requiring action",
      "Remember that disabling notifications doesn't prevent system events",
      "Don't let unread notification count grow too large - prioritize review",
      "Avoid setting all alerts to silent mode - you'll miss important events",
      "Don't forward sensitive system alerts to external emails",
    ],
    updated: "today",
  },
  {
    id: "notes",
    title: "Notes",
    category: "Collaboration",
    shortDescription: "Create and manage collaborative notes for team documentation and knowledge sharing",
    purpose: "Provides centralized location for team notes, documentation, and knowledge base. Helps teams collaborate on procedures and maintain institutional knowledge.",
    howToUse: [
      "Navigate to Notes module from the menu",
      "View all existing notes organized by category or department",
      "Click 'New Note' to create a note entry",
      "Enter note title and select appropriate category",
      "Add content using rich text editor with formatting options",
      "Tag notes with keywords for easy searching",
      "Add attachments or link related documents",
      "Share notes with team members or specific departments",
      "Collaborate by enabling edit access for team members",
      "View version history to track changes made to notes",
    ],
    importantActions: [
      "New Note - Create note entry",
      "Edit - Modify note content and formatting",
      "Share - Grant access to specific users or teams",
      "Archive - Hide completed or outdated notes",
      "Search - Find notes by keyword or tag",
      "Version History - Track and restore previous versions",
    ],
    tips: [
      "Create category structure that matches your organizational hierarchy",
      "Use consistent naming conventions for easy searching",
      "Tag notes with keywords to improve discoverability",
      "Regularly review and archive outdated notes",
      "Assign ownership to notes for accountability",
      "Use formatting to make notes more readable and scannable",
    ],
    commonMistakes: [
      "Don't create duplicate notes - search first before creating",
      "Remember that shared notes become team knowledge - document carefully",
      "Avoid storing sensitive data in notes without encryption",
      "Don't forget to update notes when procedures change",
      "Remember to grant proper access levels when sharing",
    ],
    updated: "today",
  },
  {
    id: "user-role-management",
    title: "User & Role Management",
    category: "Administration",
    shortDescription: "Manage user accounts, roles, permissions, and access control throughout the system",
    purpose: "Controls user access, defines role-based permissions, and ensures proper authorization. Critical for security and compliance.",
    howToUse: [
      "Open User & Role Management from administration area",
      "View all system users and their assigned roles",
      "Click on any user to view detailed permissions and activity",
      "Add new user by clicking 'Create User'",
      "Enter user information: name, email, department, position",
      "Assign role (Admin, Manager, Operator, Viewer, etc.)",
      "Select specific permissions needed for the role",
      "Set access restrictions (time-based, location-based if applicable)",
      "Enable or disable user account as needed",
      "Review user activity logs for security audits",
    ],
    importantActions: [
      "Create User - Add new user accounts",
      "Assign Role - Set user permissions via role assignment",
      "Edit Permissions - Customize role-based access",
      "Disable Account - Temporarily or permanently disable user access",
      "Reset Password - Help users regain access to accounts",
      "View Audit Log - Track user activities for compliance",
    ],
    tips: [
      "Use role-based access control - avoid granting individual permissions",
      "Follow principle of least privilege - grant minimum necessary access",
      "Regularly audit user access to identify unused accounts",
      "Disable accounts immediately when users leave organization",
      "Use multi-factor authentication for administrative accounts",
      "Document role definitions clearly for consistency",
    ],
    commonMistakes: [
      "Don't grant admin privileges unless absolutely necessary",
      "Remember that user access must be reviewed annually",
      "Avoid sharing admin accounts - each admin needs individual login",
      "Don't forget to disable accounts for users who leave",
      "Remember that changing roles doesn't automatically revoke old permissions",
    ],
    updated: "today",
  },
  {
    id: "settings",
    title: "Settings",
    category: "Configuration",
    shortDescription: "Configure system preferences, notification settings, and personalization options",
    purpose: "Allows users to customize their portal experience and configure system-wide preferences. Supports both personal and administrative settings.",
    howToUse: [
      "Navigate to Settings from the user profile menu (top-right)",
      "View settings organized into categories (General, Notifications, Appearance, etc.)",
      "Update personal information: name, email, department, phone",
      "Customize notification preferences and delivery methods",
      "Set theme preference (Light/Dark mode if available)",
      "Configure language and timezone for your location",
      "Manage API tokens or integrations if available",
      "Review security settings and change password if needed",
      "View and manage connected applications or devices",
      "Apply changes - settings save automatically",
    ],
    importantActions: [
      "Edit Profile - Update personal information",
      "Notifications - Configure alert preferences",
      "Security - Change password and review login history",
      "Preferences - Set language, timezone, and theme",
      "API Tokens - Manage integration credentials",
      "Connected Apps - Review and revoke application access",
    ],
    tips: [
      "Review notification settings regularly to ensure they match your needs",
      "Keep your email address current for password reset capability",
      "Use strong, unique passwords for your account",
      "Enable two-factor authentication if available for extra security",
      "Set timezone correctly for accurate timestamps in your local time",
      "Review connected applications periodically to remove unused integrations",
    ],
    commonMistakes: [
      "Don't ignore security settings - secure your account immediately",
      "Remember that changing email requires verification",
      "Avoid sharing your API tokens with others",
      "Don't enable unnecessary permissions for connected applications",
      "Remember to update your profile when your role changes",
    ],
    updated: "today",
  },
];

export function getDocumentationById(id: string): DocumentationEntry | undefined {
  return DOCUMENTATION_ENTRIES.find((doc) => doc.id === id);
}

export function searchDocumentation(query: string): DocumentationEntry[] {
  const lowerQuery = query.toLowerCase();
  return DOCUMENTATION_ENTRIES.filter(
    (doc) =>
      doc.title.toLowerCase().includes(lowerQuery) ||
      doc.shortDescription.toLowerCase().includes(lowerQuery) ||
      doc.purpose.toLowerCase().includes(lowerQuery) ||
      doc.category.toLowerCase().includes(lowerQuery)
  );
}
